instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:post_id>/delete', views.delete, name="delete"),
    path('<int:post_id>/update', views.update, name="update"),
]

posts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

posts/forms.py
from django import forms
from . models import Post

# Post라는 모델을 조작 할 수 있는 PostModelForm 정의
class PostForm(forms.ModelForm):
   # 1. 이 폼이 어떤 input field를 가지는지
   # 2. 해당 input field의 속성을 추가
   content = forms.CharField(label="content", widget = forms.Textarea(attrs={
       'placeholder': '오늘은 무엇을 하셨나요?',
   }))

   class Meta:
       model = Post
       # fields = "__all__" # __all__ : 가지고 있는 모든 필드(지금은 content가 적으나 나중에는 모델)
       fields = ['content', 'image']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post


# Create your views here.
def create(request):
    if request.method == "POST":
        # 작성된 post를 DB에 적용
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
        pass
    else: # GET
        # post를 작성하는 form을 보여줌
        form = PostForm()
        return render(request, 'posts/create.html', {'form': form})
        
        
def list(request):
    # 모든 Post를 보여줌
    Posts = Post.objects.all()
    return render(request, 'posts/list.html', {'posts': Posts})


def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
        
    post.delete()
    return redirect('posts:list')


def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user != request.user:
        return redirect('posts:list')
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    else:
        form = PostForm(instance=post)
        return render(request, 'posts/update.html', {'form': form})

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  <!--모델 폼-->
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">제출</button>
</form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
  <div class="row justify-content-center">
    {% for post in posts %}
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          <span>{{ post.user }}</span>          
        </div>
        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          <!-- 작성자만 수정/삭제 가능 -->
          {% if post.user == request.user %}
            <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">삭제</a>
            <a href="{% url 'posts:update' post.id %}" class="btn btn-success">수정</a>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <form method="POST">
      <!--모델 폼-->
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary">제출</button>
    </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!--Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <title>INSTAGRAM</title>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <i class="fab fa-instagram"></i>
    Instagram
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>